### ISSUE TITLE
Please provide an overview before going into details

### ISSUE THREAD

**Issue by guettli** [YPlan/gargoyle#109]
Please provide an overview before going into details (like how to install and how to enable it)

> https://gargoyle-yplan.readthedocs.io/en/latest/index.html

I know that is very widespread mistake. Software developers love details.

Please show the world, that you care for good docs :-)

**Comment by adamchainz** [comment]
We didn't write the docs, they came from Disqus. As the main maintainer I don't have much time to work on gargoyle atm but if you want to write said introduction, a pull request would be very welcome. Thanks.

**Comment by guettli** [comment]
I don't know what the intention of this project. I know how to create a pull request, but I have not clue what to put into the introduction.

**Comment by adamchainz** [comment]
If you're using it now, you know about as much as anyone 😄

**Comment by guettli** [comment]
Up to now I don't use it. And I guess I won't.
