### ISSUE TITLE
Crash when calling is_active: NoneType has no attribute __getitem__

### ISSUE THREAD

**Issue by kmorrison** [YPlan/gargoyle#50]
I apologize in advance for the partial stacktrace, but I work at a closed source company and I doubt they'd allow me to paste the whole thing. Below is the stacktrace starting just after we call `is_active` with the switch name and another string argument we use for conditional switching in nexus

``` 
  File "/var/www/env/local/lib/python2.7/site-packages/gargoyle/manager.py", line 59, in is_active
    switch = self[key]
  File "/var/www/env/local/lib/python2.7/site-packages/gargoyle/manager.py", line 35, in __getitem__
    return SwitchProxy(self, super(SwitchManager, self).__getitem__(key))
  File "/var/www/env/local/lib/python2.7/site-packages/modeldict/base.py", line 26, in __getitem__
    return self._local_cache[key]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

We're on `gargoyle-yplan==1.1.1`, so if you all think upgrading the package might fix this, that is certainly the next thing we'll try. As more context, we've been using gargoyle for a couple years now, we use it for _everything_, probably about a million calls a day. This error happens roughly once every 72 hours, so maybe one call per few million. We just recently switched from disqus to yplan, hence me here bothering you fine folks.

**Comment by adamchainz** [comment]
What version of `django-modeldict-yplan` are you using?

**Comment by kmorrison** [comment]
`django-modeldict-yplan==1.5.0`

**Comment by adamchainz** [comment]
Looks like this issue exists purely in `django-modeldict-yplan`. Am I right in guessing that you're using a threaded server? It seems possible for `__getitem__` to end up with `self._local_cache = None` *if* the server is threaded.

Opened YPlan/django-modeldict#18 to track the issue there now.

**Comment by adamchainz** [comment]
@kmorrison can you confirm that your using a threaded server? It will help me debug and fix the issue

**Comment by adamchainz** [comment]
Closing here but leaving YPlan/django-modeldict#18 open
