### ISSUE TITLE
Disallow empty user emails

### ISSUE THREAD

**Issue by adamchainz** [YPlan/gargoyle#55]
It's possible to add, but not remove, the email = '' condition. Removing fails with "Fields cannot be empty'.

![screen shot 2016-03-23 at 11 42 56](https://cloud.githubusercontent.com/assets/857609/13984193/8ef573c0-f0ec-11e5-823f-f92aa60c1d71.png)

**Comment by Aaron7** [comment]
This bug exists for all fields.
