### ISSUE TITLE
Multiprocess sync issue

### ISSUE THREAD

**Issue by maxiberta** [YPlan/gargoyle#83]
I've noticed that immediately after flipping (on or off) a switch which enables a certain html element, this element appears and disappears upon successive page reloads. I initially attributed this to a sync lag between gunicorn processes. It eventually settles in the expected state after around 10 minutes of constant page reloads.

I can reproduce it by running two python consoles simultaneously in the following fashion:

* One python process keeps querying the feature flag every second:
```python
>>> while True:
>>>    print gargoyle.is_active("FEATURE_UI")
>>>    time.sleep(1)
False
False
False
```
* Another python process (eg. a Python instance in another console) flips the flag:
```python
>>> gargoyle["FEATURE_UI"].status = gargoyle.GLOBAL
>>> gargoyle["FEATURE_UI"].save()
>>> print gargoyle.is_active("FEATURE_UI")
True
```
* The first process keeps getting the old value indefinitely; only syncs after 30 seconds of inactivity (30s seems to be an internal timeout in gargoyle / modeldict):
```python
False
False
False
# keeps printing False indefinitely...
```

**Comment by adamchainz** [comment]
I think your two PR's on **YPlan/django-modeldict** have fixed this!
