### ISSUE TITLE
Track switch creation date

### ISSUE THREAD

**Issue by adamchainz** [YPlan/gargoyle#89]
With lots of switches it's nice to know when it was created. Add a `created_time` field to `Switch` that auto-fills with `timezone.now` on creation, and display it in nexus.

**Comment by nkovshov** [comment]
Can't get what do you mean. `Switch` model already has `date_created = models.DateTimeField(default=now)` and it's displayed at switches list: 
![](http://i.imgur.com/O5n9JRd.png)

**Comment by adamchainz** [comment]
Yeah my bad. I don't know what I was thinking.
